# Generated by Django 4.1 on 2022-09-04 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='afm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(12)]),
        ),
    ]
