# Generated by Django 4.1 on 2022-09-06 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='afm',
            field=models.PositiveIntegerField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
