# Generated by Django 4.1 on 2022-09-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_afm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='afm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
