# Generated by Django 4.1 on 2022-09-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mybids'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currently',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='first_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_bids',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
