# Generated by Django 4.1 on 2022-09-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_product_currently'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybids',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
