# Generated by Django 4.1 on 2022-09-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_mybids_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
