# Generated by Django 4.1 on 2022-09-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
