# Generated by Django 4.1 on 2022-09-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiverName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='senderName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
