# Generated by Django 4.1 on 2022-09-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_product_currectwinner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='currectwinner',
            new_name='currentwinner',
        ),
    ]
