# Generated by Django 4.1 on 2022-09-21 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_rename_currectwinner_product_currentwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
