# Generated by Django 4.1 on 2022-09-22 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_seller_review_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybids',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
