# Generated by Django 4.1 on 2022-09-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_product_lat_alter_product_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=23, null=True),
        ),
    ]
