# Generated by Django 4.1 on 2022-09-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_product_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_viewed',
            name='id',
        ),
        migrations.AddField(
            model_name='product_viewed',
            name='_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
